services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: flashmall
    volumes:
      - ./flash-mall-user-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend1:
    build:
      context: .
      dockerfile: flash-mall-user-service/Dockerfile
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flashmall?useSSL=false&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpwd
    depends_on:
      - mysql
      - redis
    ports:
      - "8081:8081"

  backend2:
    build:
      context: .
      dockerfile: flash-mall-user-service/Dockerfile
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flashmall?useSSL=false&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpwd
    depends_on:
      - mysql
      - redis
    ports:
      - "8082:8082"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
