upstream backend_pool {
    # 默认轮询 (round-robin) — user-service
    server backend1:8081;
    server backend2:8082;
}

upstream product_pool {
    # 默认轮询 (round-robin) — product-service
    server product1:8083;
    server product2:8084;
}

upstream seckill_pool {
    # 默认轮询 (round-robin) — seckill-service
    server seckill1:8085;
    server seckill2:8086;
}

upstream order_pool {
    # 默认轮询 (round-robin) — order-service
    server order:8088;
}

upstream inventory_pool {
    # 默认轮询 (round-robin) — inventory-service
    server inventory:8087;
}
