upstream backend_pool {
    least_conn;
    server backend1:8081;
    server backend2:8082;
}

upstream product_pool {
    least_conn;
    server product1:8083;
    server product2:8084;
}

upstream seckill_pool {
    least_conn;
    server seckill1:8085;
    server seckill2:8086;
}
